"""Train the Isolation Forest model on synthetic normal data.

This script:
  1. Loads synthetic_logs.json (generated by scripts/generate_synthetic_logs.py)
  2. Extracts features (hour, day, bytes, etc.)
  3. Filters to normal-only data for training
  4. Trains and saves the model to models/isolation_forest.joblib
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import pandas as pd

from ml.model import AnomalyModel

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "synthetic_logs.json"
MODEL_OUTPUT = Path(__file__).resolve().parent.parent / "models" / "isolation_forest.joblib"

ANOMALOUS_COUNTRIES = {
    "United States",
    "China",
    "Brazil",
    "Australia",
    "Nigeria",
    "North Korea",
    "Iran",
    "Germany",
    "United Kingdom",
    "Japan",
}


def extract_features(events: list[dict]) -> pd.DataFrame:
    """Extract ML features from raw event dicts."""
    records = []
    for e in events:
        ts = datetime.fromisoformat(e["timestamp"])
        records.append(
            {
                "event_id": e["event_id"],
                "user_id": e["user_id"],
                "hour_of_day": ts.hour,
                "day_of_week": ts.weekday(),
                "minutes_from_midnight": ts.hour * 60 + ts.minute,
                "country_code": e["country"],
                "bytes_transferred": e["bytes_transferred"],
            }
        )
    return pd.DataFrame(records)


def filter_normal(df: pd.DataFrame) -> pd.DataFrame:
    """Keep only events that look 'normal' for training."""
    mask = (
        (df["hour_of_day"] >= 5)
        & (df["hour_of_day"] <= 21)
        & (~df["country_code"].isin(ANOMALOUS_COUNTRIES))
        & (df["bytes_transferred"] <= 500_000_000)
    )
    return df.loc[mask].copy()


def main() -> None:
    """Entry point."""
    if not DATA_PATH.exists():
        print(f"ERROR: {DATA_PATH} not found. Run scripts/generate_synthetic_logs.py first.")
        raise SystemExit(1)

    with open(DATA_PATH, encoding="utf-8") as f:
        events = json.load(f)

    print(f"Loaded {len(events)} events from {DATA_PATH}")

    df_all = extract_features(events)
    df_normal = filter_normal(df_all)

    print(f"Normal events for training: {len(df_normal)} / {len(df_all)}")

    model = AnomalyModel(contamination=0.05, random_state=42)
    model.train(df_normal)
    model.save(MODEL_OUTPUT)

    # Quick sanity check
    scores = model.predict(df_all)
    n_anomalies = int((scores > 0.6).sum())
    print(f"Model trained. Detected {n_anomalies} anomalies out of {len(df_all)} events.")
    print(f"Model saved to {MODEL_OUTPUT}")


if __name__ == "__main__":
    main()
